###
POST http://localhost:5000/users/register/
Content-Type: application/json

{
    "fName": "John",
    "lName": "Doe",
    "email": "John.Doe@thejitu.com",
    "password": "YourSecurePassword123@",
    "cohortNumber": "QA20"
}



### login 
POST http://localhost:5000/users/login/
Content-Type: application/json

{
   "email": "Jonathan.Ndambugi@thejitu.com",
   "password": "123456789@Jn", 
}

### fetching all users
GET http://localhost:5000/users/
token:


###update user
POST http://localhost:5000/users/updateUser/18b1d912-6bee-4648-b22d-b64ad7ac5e63/
Content-Type: application/json

{
    "fName": "Jonathan",
    "fName": "Ndambugi",
    "email": "Jonathan.Ndambugi@thejitu.com",
}

### fetching single user
GET http://localhost:5000/users/singleUser/f99ac5ee-c9da-4f7c-b719-62ae36f5b6b5/
token:  




#### deleting user
DELETE http://localhost:5000/users/delete/af604f8a-312d-4eef-b42d-d6e2ca7f11e8/
